quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASS:erika}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:15552/xerika-java?sslmode=disable}

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration

quarkus.hibernate-orm.database.generation=none

auth.issuer.url=http://localhost:8080
auth.jwt.access-token-ttl-seconds=900
auth.jwt.id-token-ttl-seconds=3600

smallrye.jwt.sign.relax-key-validation=true
